### PR TITLE
refactor code-related LLM leaderboard

### PR DESCRIPTION
**Pull request by zhimin-z**
Based on https://github.com/huybery/Awesome-Code-LLM/issues/8 Only in this way, we can make this section extensible rather than update it manually in the future. I think this could solve the static attribute of the current leaderboard.

### CODE REVIEW

**Comment by huybery** [comment]
Hi, I think we should keep manual leaderboard to prevent omissions in these exist leaderboards, such as deepseek models not being able to found in these. Wdyt?

**Comment by zhimin-z** [comment]
> Hi, I think we should keep manual leaderboard to prevent omissions in these exist leaderboards, such as deepseek models not being able to found in these. Wdyt?

Hi, I wonder where you find the evaluation of deepseek-like models? why not put their leaderboard website links together?
Why do we stop hard-coding the evaluation metrics? Because the related ranking could never be outdated, and we could include as many leaderboards as possible in the future, making the list maintenance scalable.

**Comment by huybery** [comment]
https://github.com/deepseek-ai/DeepSeek-Coder

The results of many CodeLLM exist in paper, github readme, huggingface and blogs, etc., which do not appear in the leaderboard in a timely manner. Manual maintenance has the advantage of aggregating this information so that users have to click on as few pages as possible. We could provide more leaderboard list, but maintaining a ranking table makes it easier for everyone to understand the current state of things.

**Comment by zhimin-z** [comment]
> https://github.com/deepseek-ai/DeepSeek-Coder

I agree with your point. However, it's worth noting that the metrics are readily available in the repository link itself. Since this link is already included in our list, it seems redundant to also list specific metrics. This is particularly relevant because different papers often use varying benchmarks or evaluation methods, making the metrics not directly comparable. Compiling all the evaluation metrics from different models into a single leaderboard could be misleading or cause confusion.

Alternatively, using an established leaderboard addresses these concerns. Such leaderboards ensure uniform evaluation standards, as they are vetted and agreed upon by the community. Moreover, as big code continues to evolve and grow in complexity, manually maintaining a leaderboard becomes increasingly challenging. Ensuring that all metrics are comparable, in terms of using the same evaluation harness and conditions, becomes a daunting task. I am skeptical about the scalability of a manually curated metadata collection like your list, given these challenges.

**Comment by zhimin-z** [comment]
You see, how hard it is to compare each other even using the same metrics when they do not proceed with the same prompt engineering: https://huggingface.co/blog/evaluating-mmlu-leaderboard. Here's why we need a third-party leaderboard that guarantees the model metrics are comparable.

**Comment by huybery** [comment]
The current advantage is to quickly learn about popular models in the field and their relative effects. We should try to maintain consistent settings. The advantage of manually maintaining the list is that it can quickly locate the source or paper.

**Comment by zhimin-z** [comment]
> The current advantage is to quickly learn about popular models in the field and their relative effects. We should try to maintain consistent settings. The advantage of manually maintaining the list is that it can quickly locate the source or paper.

Ok, in this case, why not include Deepseek paper and repo in the list instead?
image
If the reader wants to explore the evaluation, they could either check the leaderboard link for detailed comparison or check the paper repo directly. The only reason why I think creating a leaderboard link makes more sense is that we do not have to manually maintain the leaderboard when there are new benchmarks coming up.

**Comment by huybery** [comment]
I'm favoring both static and dynamic leaderboards, can you put the dynamic leaderboard table behind the current static table?

**Comment by zhimin-z** [comment]
> I'm favoring both static and dynamic leaderboards, can you put the dynamic leaderboard table behind the current static table?

I have a question regarding the static leaderboard currently sourced from https://github.com/deepseek-ai/deepseek-coder. My concern is about its future scalability, particularly when new, significant code models emerge that haven't showcased their Humaneval metrics in their documentation. How will these models be integrated into the leaderboard? The existing setup at https://github.com/deepseek-ai/deepseek-coder doesn't seem to support a dynamic update mechanism for new models to add their scores. This limitation could potentially render the current static leaderboard unscalable in the future.

**Comment by huybery** [comment]
The additions are great, I think the static leaderboards are still necessary, can you not remove them while keeping them?

**Comment by zhimin-z** [comment]
> The additions are great, I think the static leaderboards are still necessary, can you not remove them while keeping them?

Ok, I got the static leaderboard for reference. Now we have both :)

BTW:
I removed https://huggingface.co/spaces/bigcode/multilingual-code-evals since it is the same HTTP jump as https://huggingface.co/spaces/bigcode/bigcode-models-leaderboard. No need to have a duplicate website.

**Comment by huybery** [comment]
Thanks a lot!

**Comment by huybery** [comment]
It seems that `https://bird-bench.github.io/` leaderboard is also helpful. :)

**Pull request merged**
